services:
  bot:
    build:
      context: .
      dockerfile: infra/Dockerfile-prod
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env

volumes:
  node_modules:
